"use client";

import { useMutation, useQueryClient } from "@tanstack/react-query";
import {
  AlertCircleIcon,
  ChevronDownIcon,
  ChevronUpIcon,
  SparklesIcon,
} from "lucide-react";
import { useEffect, useRef, useState } from "react";

import { MarkdownContent } from "@/components/common/markdown-content";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from "@/components/ui/collapsible";
import { Spinner } from "@/components/ui/spinner";
import { getApiErrorMessage } from "@/lib/api-error";
import {
  type KnowledgeDocumentPreviewPublic,
  knowledgeDocumentsGenerateDocumentSummary,
} from "@/lib/client";

export function DocumentSummary({
  documentId,
  summary,
}: {
  documentId: string;
  summary: string | null;
}) {
  const queryClient = useQueryClient();

  const [open, setOpen] = useState(true);

  const autoGeneratedDocument = useRef<string | null>(null);

  const mutation = useMutation({
    mutationFn: () =>
      knowledgeDocumentsGenerateDocumentSummary({
        path: { document_id: documentId },
        throwOnError: true,
      }),
    onSuccess: ({ data }) => {
      setOpen(true);
      queryClient.setQueryData<KnowledgeDocumentPreviewPublic>(
        ["knowledge-document-preview", documentId],
        (preview) => preview && { ...preview, summary: data.content },
      );
    },
  });

  const { mutate } = mutation;

  useEffect(() => {
    if (summary || autoGeneratedDocument.current === documentId) return;

    autoGeneratedDocument.current = documentId;

    mutate();
  }, [documentId, summary, mutate]);

  let actionLabel = "生成总结";

  if (summary) actionLabel = "重新生成";
  else if (mutation.isError) actionLabel = "重试";

  return (
    <Collapsible open={open} onOpenChange={setOpen} asChild>
      <section
        aria-label="AI 总结"
        className="flex flex-col gap-4 rounded-lg bg-muted/75 p-4"
      >
        <div className="flex items-center justify-between gap-4">
          <h2 className="flex items-center gap-2 text-sm font-medium">
            <SparklesIcon
              aria-hidden="true"
              className="size-4 text-muted-foreground"
            />
            AI 总结
          </h2>
          <div className="flex items-center gap-1">
            <Button
              type="button"
              variant="ghost"
              size="sm"
              disabled={mutation.isPending}
              aria-busy={mutation.isPending}
              onClick={() => mutation.mutate()}
            >
              {mutation.isPending && <Spinner aria-hidden="true" />}
              {mutation.isPending ? "正在生成…" : actionLabel}
            </Button>
            {summary && (
              <CollapsibleTrigger asChild>
                <Button type="button" variant="ghost" size="sm">
                  {open ? (
                    <ChevronUpIcon aria-hidden="true" />
                  ) : (
                    <ChevronDownIcon aria-hidden="true" />
                  )}
                  {open ? "收起" : "展开"}
                </Button>
              </CollapsibleTrigger>
            )}
          </div>
        </div>
        {mutation.isError && (
          <Alert variant="destructive">
            <AlertCircleIcon aria-hidden="true" />
            <AlertDescription>
              {getApiErrorMessage(mutation.error, "AI 总结生成失败，请重试")}
            </AlertDescription>
          </Alert>
        )}
        {summary && (
          <CollapsibleContent className="scroll-content-y max-h-[min(24rem,50svh)]">
            <MarkdownContent className="prose-sm max-w-none [&_h1]:text-lg [&_h2]:text-base [&_h3]:text-sm">
              {summary}
            </MarkdownContent>
          </CollapsibleContent>
        )}
      </section>
    </Collapsible>
  );
}
