model_list:
  - model_name: deepseek/deepseek-v4-pro
    litellm_params:
      model: deepseek/deepseek-v4-pro
      api_key: os.environ/DEEPSEEK_API_KEY
  - model_name: deepseek/deepseek-v4-flash
    litellm_params:
      model: deepseek/deepseek-v4-flash
      api_key: os.environ/DEEPSEEK_API_KEY
  - model_name: deepseek/deepseek-v4-flash-vision-exp
    litellm_params:
      model: openai/deepseek-v4-flash-vision-exp
      api_base: https://api.deepseek.com
      api_key: os.environ/DEEPSEEK_API_KEY
      extra_body:
        thinking:
          type: disabled
  - model_name: "@cf/baai/bge-m3"
    litellm_params:
      model: openai/@cf/baai/bge-m3
      api_base: os.environ/CLOUDFLARE_AI_BASE_URL
      api_key: os.environ/CLOUDFLARE_API_KEY
      additional_drop_params:
        - encoding_format

mcp_servers:
  firecrawl:
    url: https://mcp.firecrawl.dev/v2/mcp
    transport: http
    auth_type: bearer_token
    auth_value: os.environ/FIRECRAWL_API_KEY
