# 通用的单数据库配置。

[alembic]
# 迁移脚本路径
script_location = alembic

# 用于生成迁移文件的模板
# file_template = %%(rev)s_%%(slug)s

# 渲染迁移文件内容及文件名中的日期时使用的时区。
# 字符串值会传递给 dateutil.tz.gettz()。
# 留空则使用本地时间
# timezone =

# "slug" 字段允许的最大字符数
#truncate_slug_length = 40

# 设置为 'true' 后，执行 'revision' 命令时始终运行环境，
# 不受 autogenerate 设置影响
# revision_environment = false

# 设置为 'true' 后，versions/ 目录中没有对应 .py 源文件的
# .pyc 和 .pyo 文件也会被识别为迁移版本
# sourceless = false

# 迁移版本目录配置，默认值为 alembic/versions。
# 使用多个版本目录时，初始迁移必须通过 --version-path 指定
# version_locations = %(here)s/bar %(here)s/bat alembic/versions

# 通过 script.py.mako 写入迁移文件时使用的输出编码
# output_encoding = utf-8

# 日志配置
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
