// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AddMessageCommand
 */
export type AddMessageCommand = {
    /**
     * Type
     */
    type: 'add-message';
    message: MessageInput;
    /**
     * Parentid
     */
    parentId?: string | null;
    /**
     * Sourceid
     */
    sourceId?: string | null;
};

/**
 * AddToolResultCommand
 */
export type AddToolResultCommand = {
    /**
     * Type
     */
    type: 'add-tool-result';
    /**
     * Toolcallid
     */
    toolCallId: string;
    /**
     * Toolname
     */
    toolName?: string | null;
    /**
     * Result
     */
    result: unknown;
    /**
     * Iserror
     */
    isError?: boolean | null;
    /**
     * Artifact
     */
    artifact?: unknown | null;
    /**
     * Modelcontent
     */
    modelContent?: unknown | null;
};

/**
 * AgentChatRequest
 */
export type AgentChatRequest = {
    /**
     * Threadid
     */
    threadId: string;
    /**
     * Model
     */
    model?: string | null;
    /**
     * State
     */
    state?: {
        [key: string]: unknown;
    } | null;
    /**
     * Commands
     */
    commands: Array<AddMessageCommand | AddToolResultCommand>;
};

/**
 * AgentModelPublic
 */
export type AgentModelPublic = {
    /**
     * Id
     */
    id: string;
};

/**
 * AgentModelsPublic
 */
export type AgentModelsPublic = {
    /**
     * Data
     */
    data: Array<AgentModelPublic>;
    /**
     * Defaultmodel
     */
    defaultModel: string;
};

/**
 * Body_login-login_access_token
 */
export type BodyLoginLoginAccessToken = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * ConversationDetailPublic
 */
export type ConversationDetailPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Archived
     */
    archived: boolean;
    /**
     * Createdat
     */
    createdAt: string;
    /**
     * Updatedat
     */
    updatedAt: string;
    state: ConversationStatePublic;
};

/**
 * ConversationPublic
 */
export type ConversationPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Archived
     */
    archived: boolean;
    /**
     * Createdat
     */
    createdAt: string;
    /**
     * Updatedat
     */
    updatedAt: string;
};

/**
 * ConversationRenameRequest
 */
export type ConversationRenameRequest = {
    /**
     * Title
     */
    title: string;
};

/**
 * ConversationStatePublic
 */
export type ConversationStatePublic = {
    /**
     * Messages
     */
    messages: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Todos
     */
    todos: Array<TodoPublic>;
};

/**
 * ConversationTitleRequest
 */
export type ConversationTitleRequest = {
    /**
     * Role
     */
    role: 'user';
    /**
     * Parts
     */
    parts: Array<TextMessagePart | ImageMessagePart | FileMessagePart>;
};

/**
 * ConversationsPublic
 */
export type ConversationsPublic = {
    /**
     * Data
     */
    data: Array<ConversationPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * FileMessagePart
 */
export type FileMessagePart = {
    /**
     * Type
     */
    type: 'file';
    /**
     * Data
     */
    data: string;
    /**
     * Mimetype
     */
    mimeType: string;
    /**
     * Filename
     */
    filename?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ImageMessagePart
 */
export type ImageMessagePart = {
    /**
     * Type
     */
    type: 'image';
    /**
     * Image
     */
    image: string;
    /**
     * Filename
     */
    filename?: string | null;
};

/**
 * ItemCreate
 */
export type ItemCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ItemPublic
 */
export type ItemPublic = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * ItemUpdate
 */
export type ItemUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ItemsPublic
 */
export type ItemsPublic = {
    /**
     * Data
     */
    data: Array<ItemPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Message
 */
export type MessageInput = {
    /**
     * Role
     */
    role: 'user';
    /**
     * Parts
     */
    parts: Array<TextMessagePart | ImageMessagePart | FileMessagePart>;
};

/**
 * Message
 */
export type MessageOutput = {
    /**
     * Message
     */
    message: string;
};

/**
 * TextMessagePart
 */
export type TextMessagePart = {
    /**
     * Type
     */
    type: 'text';
    /**
     * Text
     */
    text: string;
};

/**
 * TodoPublic
 */
export type TodoPublic = {
    /**
     * Content
     */
    content: string;
    /**
     * Status
     */
    status: 'pending' | 'in_progress' | 'completed';
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Username
     */
    username: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Username
     */
    username: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Username
     */
    username?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Username
     */
    username?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type LoginLoginAccessTokenData = {
    body: BodyLoginLoginAccessToken;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type LoginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginLoginAccessTokenError = LoginLoginAccessTokenErrors[keyof LoginLoginAccessTokenErrors];

export type LoginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginLoginAccessTokenResponse = LoginLoginAccessTokenResponses[keyof LoginLoginAccessTokenResponses];

export type UsersRegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type UsersRegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersRegisterUserError = UsersRegisterUserErrors[keyof UsersRegisterUserErrors];

export type UsersRegisterUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersRegisterUserResponse = UsersRegisterUserResponses[keyof UsersRegisterUserResponses];

export type UtilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type UtilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type UtilsHealthCheckResponse = UtilsHealthCheckResponses[keyof UtilsHealthCheckResponses];

export type LoginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type LoginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type LoginTestTokenResponse = LoginTestTokenResponses[keyof LoginTestTokenResponses];

export type UsersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: MessageOutput;
};

export type UsersDeleteUserMeResponse = UsersDeleteUserMeResponses[keyof UsersDeleteUserMeResponses];

export type UsersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersReadUserMeResponse = UsersReadUserMeResponses[keyof UsersReadUserMeResponses];

export type UsersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdateUserMeError = UsersUpdateUserMeErrors[keyof UsersUpdateUserMeErrors];

export type UsersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersUpdateUserMeResponse = UsersUpdateUserMeResponses[keyof UsersUpdateUserMeResponses];

export type UsersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type UsersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdatePasswordMeError = UsersUpdatePasswordMeErrors[keyof UsersUpdatePasswordMeErrors];

export type UsersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: MessageOutput;
};

export type UsersUpdatePasswordMeResponse = UsersUpdatePasswordMeResponses[keyof UsersUpdatePasswordMeResponses];

export type UsersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersDeleteUserError = UsersDeleteUserErrors[keyof UsersDeleteUserErrors];

export type UsersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: MessageOutput;
};

export type UsersDeleteUserResponse = UsersDeleteUserResponses[keyof UsersDeleteUserResponses];

export type UsersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersReadUserByIdError = UsersReadUserByIdErrors[keyof UsersReadUserByIdErrors];

export type UsersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersReadUserByIdResponse = UsersReadUserByIdResponses[keyof UsersReadUserByIdResponses];

export type UsersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdateUserError = UsersUpdateUserErrors[keyof UsersUpdateUserErrors];

export type UsersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersUpdateUserResponse = UsersUpdateUserResponses[keyof UsersUpdateUserResponses];

export type UsersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type UsersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersReadUsersError = UsersReadUsersErrors[keyof UsersReadUsersErrors];

export type UsersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type UsersReadUsersResponse = UsersReadUsersResponses[keyof UsersReadUsersResponses];

export type UsersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type UsersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersCreateUserError = UsersCreateUserErrors[keyof UsersCreateUserErrors];

export type UsersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersCreateUserResponse = UsersCreateUserResponses[keyof UsersCreateUserResponses];

export type ItemsReadItemsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/items/';
};

export type ItemsReadItemsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsReadItemsError = ItemsReadItemsErrors[keyof ItemsReadItemsErrors];

export type ItemsReadItemsResponses = {
    /**
     * Successful Response
     */
    200: ItemsPublic;
};

export type ItemsReadItemsResponse = ItemsReadItemsResponses[keyof ItemsReadItemsResponses];

export type ItemsCreateItemData = {
    body: ItemCreate;
    path?: never;
    query?: never;
    url: '/api/v1/items/';
};

export type ItemsCreateItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsCreateItemError = ItemsCreateItemErrors[keyof ItemsCreateItemErrors];

export type ItemsCreateItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type ItemsCreateItemResponse = ItemsCreateItemResponses[keyof ItemsCreateItemResponses];

export type ItemsDeleteItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type ItemsDeleteItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsDeleteItemError = ItemsDeleteItemErrors[keyof ItemsDeleteItemErrors];

export type ItemsDeleteItemResponses = {
    /**
     * Successful Response
     */
    200: MessageOutput;
};

export type ItemsDeleteItemResponse = ItemsDeleteItemResponses[keyof ItemsDeleteItemResponses];

export type ItemsReadItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type ItemsReadItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsReadItemError = ItemsReadItemErrors[keyof ItemsReadItemErrors];

export type ItemsReadItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type ItemsReadItemResponse = ItemsReadItemResponses[keyof ItemsReadItemResponses];

export type ItemsUpdateItemData = {
    body: ItemUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type ItemsUpdateItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsUpdateItemError = ItemsUpdateItemErrors[keyof ItemsUpdateItemErrors];

export type ItemsUpdateItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type ItemsUpdateItemResponse = ItemsUpdateItemResponses[keyof ItemsUpdateItemResponses];

export type AgentReadConversationsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/agent/conversations';
};

export type AgentReadConversationsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AgentReadConversationsError = AgentReadConversationsErrors[keyof AgentReadConversationsErrors];

export type AgentReadConversationsResponses = {
    /**
     * Successful Response
     */
    200: ConversationsPublic;
};

export type AgentReadConversationsResponse = AgentReadConversationsResponses[keyof AgentReadConversationsResponses];

export type AgentCreateConversationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/agent/conversations';
};

export type AgentCreateConversationResponses = {
    /**
     * Successful Response
     */
    201: ConversationPublic;
};

export type AgentCreateConversationResponse = AgentCreateConversationResponses[keyof AgentCreateConversationResponses];

export type AgentGenerateConversationTitleData = {
    body: ConversationTitleRequest;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/v1/agent/conversations/{conversation_id}/generate-title';
};

export type AgentGenerateConversationTitleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AgentGenerateConversationTitleError = AgentGenerateConversationTitleErrors[keyof AgentGenerateConversationTitleErrors];

export type AgentGenerateConversationTitleResponses = {
    /**
     * Successful Response
     */
    200: ConversationPublic;
};

export type AgentGenerateConversationTitleResponse = AgentGenerateConversationTitleResponses[keyof AgentGenerateConversationTitleResponses];

export type AgentDeleteConversationData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/v1/agent/conversations/{conversation_id}';
};

export type AgentDeleteConversationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AgentDeleteConversationError = AgentDeleteConversationErrors[keyof AgentDeleteConversationErrors];

export type AgentDeleteConversationResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type AgentDeleteConversationResponse = AgentDeleteConversationResponses[keyof AgentDeleteConversationResponses];

export type AgentReadConversationData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/v1/agent/conversations/{conversation_id}';
};

export type AgentReadConversationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AgentReadConversationError = AgentReadConversationErrors[keyof AgentReadConversationErrors];

export type AgentReadConversationResponses = {
    /**
     * Successful Response
     */
    200: ConversationDetailPublic;
};

export type AgentReadConversationResponse = AgentReadConversationResponses[keyof AgentReadConversationResponses];

export type AgentRenameConversationData = {
    body: ConversationRenameRequest;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/v1/agent/conversations/{conversation_id}';
};

export type AgentRenameConversationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AgentRenameConversationError = AgentRenameConversationErrors[keyof AgentRenameConversationErrors];

export type AgentRenameConversationResponses = {
    /**
     * Successful Response
     */
    200: ConversationPublic;
};

export type AgentRenameConversationResponse = AgentRenameConversationResponses[keyof AgentRenameConversationResponses];

export type AgentArchiveConversationData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/v1/agent/conversations/{conversation_id}/archive';
};

export type AgentArchiveConversationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AgentArchiveConversationError = AgentArchiveConversationErrors[keyof AgentArchiveConversationErrors];

export type AgentArchiveConversationResponses = {
    /**
     * Successful Response
     */
    200: ConversationPublic;
};

export type AgentArchiveConversationResponse = AgentArchiveConversationResponses[keyof AgentArchiveConversationResponses];

export type AgentUnarchiveConversationData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/v1/agent/conversations/{conversation_id}/unarchive';
};

export type AgentUnarchiveConversationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AgentUnarchiveConversationError = AgentUnarchiveConversationErrors[keyof AgentUnarchiveConversationErrors];

export type AgentUnarchiveConversationResponses = {
    /**
     * Successful Response
     */
    200: ConversationPublic;
};

export type AgentUnarchiveConversationResponse = AgentUnarchiveConversationResponses[keyof AgentUnarchiveConversationResponses];

export type AgentReadModelsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/agent/models';
};

export type AgentReadModelsResponses = {
    /**
     * Successful Response
     */
    200: AgentModelsPublic;
};

export type AgentReadModelsResponse = AgentReadModelsResponses[keyof AgentReadModelsResponses];

export type AgentChatData = {
    body: AgentChatRequest;
    path?: never;
    query?: never;
    url: '/api/v1/agent/chat';
};

export type AgentChatErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AgentChatError = AgentChatErrors[keyof AgentChatErrors];

export type AgentChatResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
