// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AddMessageCommand
 */
export type AddMessageCommand = {
    /**
     * Type
     */
    type: 'add-message';
    message: MessageInput;
    /**
     * Parentid
     */
    parentId?: string | null;
    /**
     * Sourceid
     */
    sourceId?: string | null;
};

/**
 * AddToolResultCommand
 */
export type AddToolResultCommand = {
    /**
     * Type
     */
    type: 'add-tool-result';
    /**
     * Toolcallid
     */
    toolCallId: string;
    /**
     * Toolname
     */
    toolName?: string | null;
    /**
     * Result
     */
    result: unknown;
    /**
     * Iserror
     */
    isError?: boolean | null;
    /**
     * Artifact
     */
    artifact?: unknown | null;
    /**
     * Modelcontent
     */
    modelContent?: unknown | null;
};

/**
 * AgentChatRequest
 */
export type AgentChatRequest = {
    /**
     * Threadid
     */
    threadId: string;
    /**
     * Model
     */
    model?: string | null;
    /**
     * Thinkingenabled
     */
    thinkingEnabled?: boolean;
    /**
     * State
     */
    state: {
        [key: string]: unknown;
    };
    /**
     * Commands
     */
    commands: Array<AddMessageCommand | AddToolResultCommand>;
};

/**
 * AgentModelPublic
 */
export type AgentModelPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Supportsthinking
     */
    supportsThinking: boolean;
};

/**
 * AgentModelsPublic
 */
export type AgentModelsPublic = {
    /**
     * Data
     */
    data: Array<AgentModelPublic>;
    /**
     * Defaultmodel
     */
    defaultModel: string;
};

/**
 * AgentRunResumeStatePublic
 */
export type AgentRunResumeStatePublic = {
    /**
     * Runid
     */
    runId: string;
    /**
     * State
     */
    state: {
        [key: string]: unknown;
    };
};

/**
 * AgentRunResumeStateRequest
 */
export type AgentRunResumeStateRequest = {
    /**
     * Threadid
     */
    threadId: string;
};

/**
 * ArtifactPublic
 */
export type ArtifactPublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Url
     */
    url: string;
    /**
     * Contenttype
     */
    contentType: string;
};

/**
 * BilibiliRankingCategoryCode
 */
export type BilibiliRankingCategoryCode = 'all' | 'animation' | 'game' | 'kichiku' | 'music' | 'dance' | 'cinephile' | 'entertainment' | 'knowledge' | 'tech' | 'food' | 'car' | 'fashion' | 'sports';

/**
 * BilibiliRankingCategoryPublic
 */
export type BilibiliRankingCategoryPublic = {
    code: BilibiliRankingCategoryCode;
    /**
     * Name
     */
    name: string;
};

/**
 * BilibiliRankingItemPublic
 */
export type BilibiliRankingItemPublic = {
    /**
     * Rank
     */
    rank: number;
    /**
     * Bvid
     */
    bvid: string;
    /**
     * Title
     */
    title: string;
    /**
     * Cover Url
     */
    cover_url: string;
    /**
     * Duration Seconds
     */
    duration_seconds: number;
    /**
     * Author Name
     */
    author_name: string;
    /**
     * Content Category Name
     */
    content_category_name: string;
    /**
     * View Count
     */
    view_count: number;
    /**
     * Danmaku Count
     */
    danmaku_count: number;
    /**
     * Published At
     */
    published_at: string;
};

/**
 * BilibiliRankingPublic
 */
export type BilibiliRankingPublic = {
    /**
     * Captured At
     */
    captured_at: string | null;
    /**
     * Categories
     */
    categories: Array<BilibiliRankingCategoryPublic>;
    /**
     * Data
     */
    data: Array<BilibiliRankingItemPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Body_login-login_access_token
 */
export type BodyLoginLoginAccessToken = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * Body_skills-create_zip_skill
 */
export type BodySkillsCreateZipSkill = {
    /**
     * Skill Zip
     */
    skill_zip: Blob | File;
};

/**
 * ConversationDetailPublic
 */
export type ConversationDetailPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Archived
     */
    archived: boolean;
    /**
     * Createdat
     */
    createdAt: string;
    /**
     * Updatedat
     */
    updatedAt: string;
    state: ConversationStatePublic;
};

/**
 * ConversationPublic
 */
export type ConversationPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Archived
     */
    archived: boolean;
    /**
     * Createdat
     */
    createdAt: string;
    /**
     * Updatedat
     */
    updatedAt: string;
};

/**
 * ConversationRenameRequest
 */
export type ConversationRenameRequest = {
    /**
     * Title
     */
    title: string;
};

/**
 * ConversationStatePublic
 */
export type ConversationStatePublic = {
    /**
     * Messages
     */
    messages: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Todos
     */
    todos: Array<TodoPublic>;
    /**
     * Artifacts
     */
    artifacts: Array<ArtifactPublic>;
};

/**
 * ConversationTitleRequest
 */
export type ConversationTitleRequest = {
    /**
     * Role
     */
    role: 'user';
    /**
     * Parts
     */
    parts: Array<TextMessagePart | ImageMessagePart | FileMessagePart>;
};

/**
 * ConversationsPublic
 */
export type ConversationsPublic = {
    /**
     * Data
     */
    data: Array<ConversationPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * FileCompletePublic
 */
export type FileCompletePublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Downloadurl
     */
    downloadUrl: string;
};

/**
 * FileMessagePart
 */
export type FileMessagePart = {
    /**
     * Type
     */
    type: 'file';
    /**
     * Data
     */
    data: string;
    /**
     * Mimetype
     */
    mimeType: string;
    /**
     * Filename
     */
    filename?: string | null;
};

/**
 * FileUploadPublic
 */
export type FileUploadPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Uploadurl
     */
    uploadUrl: string;
    /**
     * Uploadheaders
     */
    uploadHeaders: {
        [key: string]: string;
    };
};

/**
 * FileUploadRequest
 */
export type FileUploadRequest = {
    /**
     * Filename
     */
    filename: string;
    /**
     * Contenttype
     */
    contentType: string;
    /**
     * Size
     */
    size: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ImageMessagePart
 */
export type ImageMessagePart = {
    /**
     * Type
     */
    type: 'image';
    /**
     * Image
     */
    image: string;
    /**
     * Filename
     */
    filename?: string | null;
};

/**
 * InfluencerAccountPublic
 */
export type InfluencerAccountPublic = {
    /**
     * Public Account Id
     */
    public_account_id: string;
    /**
     * Nickname
     */
    nickname: string;
    /**
     * Avatar Url
     */
    avatar_url: string | null;
    /**
     * Profile Url
     */
    profile_url: string;
    /**
     * Location
     */
    location: string | null;
    /**
     * Bio
     */
    bio: string | null;
    /**
     * Followers
     */
    followers: number;
    /**
     * Engagement Count
     */
    engagement_count: number | null;
};

/**
 * InfluencerAccountSortBy
 */
export type InfluencerAccountSortBy = 'followers' | 'engagement_count';

/**
 * InfluencerAccountsPublic
 */
export type InfluencerAccountsPublic = {
    /**
     * Captured At
     */
    captured_at: string | null;
    /**
     * Data
     */
    data: Array<InfluencerAccountPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * InfluencerPlatformCode
 */
export type InfluencerPlatformCode = 'douyin' | 'xiaohongshu';

/**
 * InfluencerSortOrder
 */
export type InfluencerSortOrder = 'asc' | 'desc';

export type JsonValue = unknown;

/**
 * KnowledgeBaseCreate
 */
export type KnowledgeBaseCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * KnowledgeBasePublic
 */
export type KnowledgeBasePublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Is Enabled
     */
    is_enabled: boolean;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * KnowledgeBaseUpdate
 */
export type KnowledgeBaseUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Is Enabled
     */
    is_enabled?: boolean | null;
};

/**
 * KnowledgeBasesPublic
 */
export type KnowledgeBasesPublic = {
    /**
     * Data
     */
    data: Array<KnowledgeBasePublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * KnowledgeDirectoryDelete
 */
export type KnowledgeDirectoryDelete = {
    /**
     * Folder Ids
     */
    folder_ids?: Array<string>;
    /**
     * Document Ids
     */
    document_ids?: Array<string>;
};

/**
 * KnowledgeDirectoryPublic
 */
export type KnowledgeDirectoryPublic = {
    /**
     * Data
     */
    data: Array<KnowledgeFolderEntryPublic | KnowledgeDocumentEntryPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * KnowledgeDocumentChunkPublic
 */
export type KnowledgeDocumentChunkPublic = {
    /**
     * Chunk Index
     */
    chunk_index: number;
    /**
     * Content
     */
    content: string;
    /**
     * Section Path
     */
    section_path: Array<string>;
    /**
     * Page Numbers
     */
    page_numbers: Array<number>;
    /**
     * Image Urls
     */
    image_urls: Array<string>;
};

/**
 * KnowledgeDocumentChunksPublic
 */
export type KnowledgeDocumentChunksPublic = {
    /**
     * Data
     */
    data: Array<KnowledgeDocumentChunkPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * KnowledgeDocumentEntryPublic
 */
export type KnowledgeDocumentEntryPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Knowledge Base Id
     */
    knowledge_base_id: string;
    /**
     * Folder Id
     */
    folder_id: string | null;
    /**
     * Filename
     */
    filename: string;
    /**
     * Content Type
     */
    content_type: string;
    /**
     * Size
     */
    size: number;
    /**
     * Uploaded
     */
    uploaded: boolean;
    /**
     * Source Url
     */
    source_url: string | null;
    status: KnowledgeDocumentStatus;
    /**
     * Error Message
     */
    error_message: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Type
     */
    type: 'document';
};

/**
 * KnowledgeDocumentMove
 */
export type KnowledgeDocumentMove = {
    /**
     * Folder Id
     */
    folder_id: string | null;
};

/**
 * KnowledgeDocumentPreviewPublic
 */
export type KnowledgeDocumentPreviewPublic = {
    /**
     * Filename
     */
    filename: string;
    /**
     * Content
     */
    content: string;
};

/**
 * KnowledgeDocumentPublic
 */
export type KnowledgeDocumentPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Knowledge Base Id
     */
    knowledge_base_id: string;
    /**
     * Folder Id
     */
    folder_id: string | null;
    /**
     * Filename
     */
    filename: string;
    /**
     * Content Type
     */
    content_type: string;
    /**
     * Size
     */
    size: number;
    /**
     * Uploaded
     */
    uploaded: boolean;
    /**
     * Source Url
     */
    source_url: string | null;
    status: KnowledgeDocumentStatus;
    /**
     * Error Message
     */
    error_message: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * KnowledgeDocumentStatus
 */
export type KnowledgeDocumentStatus = 'pending' | 'processing' | 'ready' | 'failed' | 'timed_out';

/**
 * KnowledgeDocumentUploadPublic
 */
export type KnowledgeDocumentUploadPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Uploadurl
     */
    uploadUrl: string;
    /**
     * Uploadheaders
     */
    uploadHeaders: {
        [key: string]: string;
    };
};

/**
 * KnowledgeFolderCreate
 */
export type KnowledgeFolderCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Parent Id
     */
    parent_id?: string | null;
};

/**
 * KnowledgeFolderEntryPublic
 */
export type KnowledgeFolderEntryPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Knowledge Base Id
     */
    knowledge_base_id: string;
    /**
     * Parent Id
     */
    parent_id: string | null;
    /**
     * Name
     */
    name: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Type
     */
    type: 'folder';
};

/**
 * KnowledgeFolderMove
 */
export type KnowledgeFolderMove = {
    /**
     * Parent Id
     */
    parent_id: string | null;
};

/**
 * KnowledgeFolderPublic
 */
export type KnowledgeFolderPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Knowledge Base Id
     */
    knowledge_base_id: string;
    /**
     * Parent Id
     */
    parent_id: string | null;
    /**
     * Name
     */
    name: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * KnowledgeFolderUpdate
 */
export type KnowledgeFolderUpdate = {
    /**
     * Name
     */
    name: string;
};

/**
 * KnowledgeFoldersPublic
 */
export type KnowledgeFoldersPublic = {
    /**
     * Data
     */
    data: Array<KnowledgeFolderPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * KnowledgeSearchRequest
 */
export type KnowledgeSearchRequest = {
    /**
     * Query
     */
    query: string;
};

/**
 * KnowledgeSearchResultPublic
 */
export type KnowledgeSearchResultPublic = {
    /**
     * Document Id
     */
    document_id: string;
    /**
     * Chunk Index
     */
    chunk_index: number;
    /**
     * Knowledge Base Name
     */
    knowledge_base_name: string;
    /**
     * Filename
     */
    filename: string;
    /**
     * Content
     */
    content: string;
    /**
     * Section Path
     */
    section_path: Array<string>;
    /**
     * Page Numbers
     */
    page_numbers: Array<number>;
    /**
     * Image Urls
     */
    image_urls: Array<string>;
    /**
     * Score
     */
    score: number;
};

/**
 * KnowledgeSearchResultsPublic
 */
export type KnowledgeSearchResultsPublic = {
    /**
     * Data
     */
    data: Array<KnowledgeSearchResultPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * KnowledgeWebpageCreate
 */
export type KnowledgeWebpageCreate = {
    /**
     * Url
     */
    url: string;
};

/**
 * Message
 */
export type MessageInput = {
    /**
     * Role
     */
    role: 'user';
    /**
     * Parts
     */
    parts: Array<TextMessagePart | ImageMessagePart | FileMessagePart>;
};

/**
 * Message
 */
export type MessageOutput = {
    /**
     * Message
     */
    message: string;
};

/**
 * ProvinceAnnualDataPublic
 */
export type ProvinceAnnualDataPublic = {
    /**
     * Province Code
     */
    province_code: string;
    /**
     * Province Name
     */
    province_name: string;
    /**
     * Resident Population
     */
    resident_population: number;
    /**
     * Resident Population Yoy
     */
    resident_population_yoy: number | null;
    /**
     * Urbanization Rate
     */
    urbanization_rate: number | null;
    /**
     * Urbanization Rate Yoy
     */
    urbanization_rate_yoy: number | null;
    /**
     * Per Capita Gdp
     */
    per_capita_gdp: number;
    /**
     * Per Capita Gdp Yoy
     */
    per_capita_gdp_yoy: number | null;
    /**
     * Disposable Income
     */
    disposable_income: number;
    /**
     * Disposable Income Yoy
     */
    disposable_income_yoy: number | null;
    /**
     * Consumption Expenditure
     */
    consumption_expenditure: number;
    /**
     * Consumption Expenditure Yoy
     */
    consumption_expenditure_yoy: number | null;
    /**
     * Retail Sales
     */
    retail_sales: number;
    /**
     * Retail Sales Yoy
     */
    retail_sales_yoy: number | null;
};

/**
 * RegionalDataPublic
 */
export type RegionalDataPublic = {
    /**
     * Year
     */
    year: number | null;
    /**
     * Years
     */
    years: Array<number>;
    /**
     * Indicators
     */
    indicators: Array<RegionalIndicatorPublic>;
    /**
     * Data
     */
    data: Array<ProvinceAnnualDataPublic>;
    /**
     * Count
     */
    count: number;
    /**
     * Source
     */
    source: string;
};

/**
 * RegionalIndicatorCode
 */
export type RegionalIndicatorCode = 'resident_population' | 'urbanization_rate' | 'per_capita_gdp' | 'disposable_income' | 'consumption_expenditure' | 'retail_sales';

/**
 * RegionalIndicatorPublic
 */
export type RegionalIndicatorPublic = {
    code: RegionalIndicatorCode;
    /**
     * Name
     */
    name: string;
    /**
     * Unit
     */
    unit: string;
};

/**
 * RegionalSortOrder
 */
export type RegionalSortOrder = 'asc' | 'desc';

/**
 * SkillFileNodePublic
 */
export type SkillFileNodePublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Path
     */
    path: string;
    /**
     * Type
     */
    type: 'file' | 'folder';
    /**
     * Children
     */
    children?: Array<SkillFileNodePublic> | null;
};

/**
 * SkillMdRequest
 */
export type SkillMdRequest = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
    /**
     * Content
     */
    content: string;
};

/**
 * SkillPublic
 */
export type SkillPublic = {
    /**
     * Frontmatter
     */
    frontmatter: {
        [key: string]: JsonValue;
    };
    /**
     * Content
     */
    content: string;
    /**
     * Filecount
     */
    fileCount: number;
    /**
     * Files
     */
    files: Array<SkillFileNodePublic>;
};

/**
 * SkillSummaryPublic
 */
export type SkillSummaryPublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
};

/**
 * SkillsPublic
 */
export type SkillsPublic = {
    /**
     * Data
     */
    data: Array<SkillSummaryPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * TextMessagePart
 */
export type TextMessagePart = {
    /**
     * Type
     */
    type: 'text';
    /**
     * Text
     */
    text: string;
};

/**
 * TodoPublic
 */
export type TodoPublic = {
    /**
     * Content
     */
    content: string;
    /**
     * Status
     */
    status: 'pending' | 'in_progress' | 'completed';
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Username
     */
    username: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Username
     */
    username: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Username
     */
    username?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Username
     */
    username?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type LoginLoginAccessTokenData = {
    body: BodyLoginLoginAccessToken;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type LoginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginLoginAccessTokenError = LoginLoginAccessTokenErrors[keyof LoginLoginAccessTokenErrors];

export type LoginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginLoginAccessTokenResponse = LoginLoginAccessTokenResponses[keyof LoginLoginAccessTokenResponses];

export type UsersRegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type UsersRegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersRegisterUserError = UsersRegisterUserErrors[keyof UsersRegisterUserErrors];

export type UsersRegisterUserResponses = {
    /**
     * Successful Response
     */
    201: UserPublic;
};

export type UsersRegisterUserResponse = UsersRegisterUserResponses[keyof UsersRegisterUserResponses];

export type UtilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type UtilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type UtilsHealthCheckResponse = UtilsHealthCheckResponses[keyof UtilsHealthCheckResponses];

export type LoginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type LoginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type LoginTestTokenResponse = LoginTestTokenResponses[keyof LoginTestTokenResponses];

export type UsersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type UsersDeleteUserMeResponse = UsersDeleteUserMeResponses[keyof UsersDeleteUserMeResponses];

export type UsersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersReadUserMeResponse = UsersReadUserMeResponses[keyof UsersReadUserMeResponses];

export type UsersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdateUserMeError = UsersUpdateUserMeErrors[keyof UsersUpdateUserMeErrors];

export type UsersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersUpdateUserMeResponse = UsersUpdateUserMeResponses[keyof UsersUpdateUserMeResponses];

export type UsersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type UsersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdatePasswordMeError = UsersUpdatePasswordMeErrors[keyof UsersUpdatePasswordMeErrors];

export type UsersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: MessageOutput;
};

export type UsersUpdatePasswordMeResponse = UsersUpdatePasswordMeResponses[keyof UsersUpdatePasswordMeResponses];

export type UsersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersDeleteUserError = UsersDeleteUserErrors[keyof UsersDeleteUserErrors];

export type UsersDeleteUserResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type UsersDeleteUserResponse = UsersDeleteUserResponses[keyof UsersDeleteUserResponses];

export type UsersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersReadUserByIdError = UsersReadUserByIdErrors[keyof UsersReadUserByIdErrors];

export type UsersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersReadUserByIdResponse = UsersReadUserByIdResponses[keyof UsersReadUserByIdResponses];

export type UsersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdateUserError = UsersUpdateUserErrors[keyof UsersUpdateUserErrors];

export type UsersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersUpdateUserResponse = UsersUpdateUserResponses[keyof UsersUpdateUserResponses];

export type UsersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Search
         */
        search?: string | null;
        /**
         * Is Superuser
         */
        is_superuser?: boolean | null;
        /**
         * Is Active
         */
        is_active?: boolean | null;
    };
    url: '/api/v1/users';
};

export type UsersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersReadUsersError = UsersReadUsersErrors[keyof UsersReadUsersErrors];

export type UsersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type UsersReadUsersResponse = UsersReadUsersResponses[keyof UsersReadUsersResponses];

export type UsersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users';
};

export type UsersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersCreateUserError = UsersCreateUserErrors[keyof UsersCreateUserErrors];

export type UsersCreateUserResponses = {
    /**
     * Successful Response
     */
    201: UserPublic;
};

export type UsersCreateUserResponse = UsersCreateUserResponses[keyof UsersCreateUserResponses];

export type BrandMarketingReadRegionalDataData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Year
         */
        year?: number | null;
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        sort_by?: RegionalIndicatorCode;
        sort_order?: RegionalSortOrder;
    };
    url: '/api/v1/admin/brand-marketing/regional-data';
};

export type BrandMarketingReadRegionalDataErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BrandMarketingReadRegionalDataError = BrandMarketingReadRegionalDataErrors[keyof BrandMarketingReadRegionalDataErrors];

export type BrandMarketingReadRegionalDataResponses = {
    /**
     * Successful Response
     */
    200: RegionalDataPublic;
};

export type BrandMarketingReadRegionalDataResponse = BrandMarketingReadRegionalDataResponses[keyof BrandMarketingReadRegionalDataResponses];

export type KnowledgeBasesReadKnowledgeBasesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Search
         */
        search?: string | null;
        /**
         * Is Enabled
         */
        is_enabled?: boolean | null;
    };
    url: '/api/v1/admin/knowledge-bases';
};

export type KnowledgeBasesReadKnowledgeBasesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type KnowledgeBasesReadKnowledgeBasesError = KnowledgeBasesReadKnowledgeBasesErrors[keyof KnowledgeBasesReadKnowledgeBasesErrors];

export type KnowledgeBasesReadKnowledgeBasesResponses = {
    /**
     * Successful Response
     */
    200: KnowledgeBasesPublic;
};

export type KnowledgeBasesReadKnowledgeBasesResponse = KnowledgeBasesReadKnowledgeBasesResponses[keyof KnowledgeBasesReadKnowledgeBasesResponses];

export type KnowledgeBasesCreateKnowledgeBaseData = {
    body: KnowledgeBaseCreate;
    path?: never;
    query?: never;
    url: '/api/v1/admin/knowledge-bases';
};

export type KnowledgeBasesCreateKnowledgeBaseErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type KnowledgeBasesCreateKnowledgeBaseError = KnowledgeBasesCreateKnowledgeBaseErrors[keyof KnowledgeBasesCreateKnowledgeBaseErrors];

export type KnowledgeBasesCreateKnowledgeBaseResponses = {
    /**
     * Successful Response
     */
    201: KnowledgeBasePublic;
};

export type KnowledgeBasesCreateKnowledgeBaseResponse = KnowledgeBasesCreateKnowledgeBaseResponses[keyof KnowledgeBasesCreateKnowledgeBaseResponses];

export type KnowledgeBasesDeleteKnowledgeBaseData = {
    body?: never;
    path: {
        /**
         * Knowledge Base Id
         */
        knowledge_base_id: string;
    };
    query?: never;
    url: '/api/v1/admin/knowledge-bases/{knowledge_base_id}';
};

export type KnowledgeBasesDeleteKnowledgeBaseErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type KnowledgeBasesDeleteKnowledgeBaseError = KnowledgeBasesDeleteKnowledgeBaseErrors[keyof KnowledgeBasesDeleteKnowledgeBaseErrors];

export type KnowledgeBasesDeleteKnowledgeBaseResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type KnowledgeBasesDeleteKnowledgeBaseResponse = KnowledgeBasesDeleteKnowledgeBaseResponses[keyof KnowledgeBasesDeleteKnowledgeBaseResponses];

export type KnowledgeBasesReadKnowledgeBaseData = {
    body?: never;
    path: {
        /**
         * Knowledge Base Id
         */
        knowledge_base_id: string;
    };
    query?: never;
    url: '/api/v1/admin/knowledge-bases/{knowledge_base_id}';
};

export type KnowledgeBasesReadKnowledgeBaseErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type KnowledgeBasesReadKnowledgeBaseError = KnowledgeBasesReadKnowledgeBaseErrors[keyof KnowledgeBasesReadKnowledgeBaseErrors];

export type KnowledgeBasesReadKnowledgeBaseResponses = {
    /**
     * Successful Response
     */
    200: KnowledgeBasePublic;
};

export type KnowledgeBasesReadKnowledgeBaseResponse = KnowledgeBasesReadKnowledgeBaseResponses[keyof KnowledgeBasesReadKnowledgeBaseResponses];

export type KnowledgeBasesUpdateKnowledgeBaseData = {
    body: KnowledgeBaseUpdate;
    path: {
        /**
         * Knowledge Base Id
         */
        knowledge_base_id: string;
    };
    query?: never;
    url: '/api/v1/admin/knowledge-bases/{knowledge_base_id}';
};

export type KnowledgeBasesUpdateKnowledgeBaseErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type KnowledgeBasesUpdateKnowledgeBaseError = KnowledgeBasesUpdateKnowledgeBaseErrors[keyof KnowledgeBasesUpdateKnowledgeBaseErrors];

export type KnowledgeBasesUpdateKnowledgeBaseResponses = {
    /**
     * Successful Response
     */
    200: KnowledgeBasePublic;
};

export type KnowledgeBasesUpdateKnowledgeBaseResponse = KnowledgeBasesUpdateKnowledgeBaseResponses[keyof KnowledgeBasesUpdateKnowledgeBaseResponses];

export type KnowledgeBasesReadFoldersData = {
    body?: never;
    path: {
        /**
         * Knowledge Base Id
         */
        knowledge_base_id: string;
    };
    query?: never;
    url: '/api/v1/admin/knowledge-bases/{knowledge_base_id}/folders';
};

export type KnowledgeBasesReadFoldersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type KnowledgeBasesReadFoldersError = KnowledgeBasesReadFoldersErrors[keyof KnowledgeBasesReadFoldersErrors];

export type KnowledgeBasesReadFoldersResponses = {
    /**
     * Successful Response
     */
    200: KnowledgeFoldersPublic;
};

export type KnowledgeBasesReadFoldersResponse = KnowledgeBasesReadFoldersResponses[keyof KnowledgeBasesReadFoldersResponses];

export type KnowledgeBasesCreateFolderData = {
    body: KnowledgeFolderCreate;
    path: {
        /**
         * Knowledge Base Id
         */
        knowledge_base_id: string;
    };
    query?: never;
    url: '/api/v1/admin/knowledge-bases/{knowledge_base_id}/folders';
};

export type KnowledgeBasesCreateFolderErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type KnowledgeBasesCreateFolderError = KnowledgeBasesCreateFolderErrors[keyof KnowledgeBasesCreateFolderErrors];

export type KnowledgeBasesCreateFolderResponses = {
    /**
     * Successful Response
     */
    201: KnowledgeFolderPublic;
};

export type KnowledgeBasesCreateFolderResponse = KnowledgeBasesCreateFolderResponses[keyof KnowledgeBasesCreateFolderResponses];

export type KnowledgeBasesUpdateFolderData = {
    body: KnowledgeFolderUpdate;
    path: {
        /**
         * Knowledge Base Id
         */
        knowledge_base_id: string;
        /**
         * Folder Id
         */
        folder_id: string;
    };
    query?: never;
    url: '/api/v1/admin/knowledge-bases/{knowledge_base_id}/folders/{folder_id}';
};

export type KnowledgeBasesUpdateFolderErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type KnowledgeBasesUpdateFolderError = KnowledgeBasesUpdateFolderErrors[keyof KnowledgeBasesUpdateFolderErrors];

export type KnowledgeBasesUpdateFolderResponses = {
    /**
     * Successful Response
     */
    200: KnowledgeFolderPublic;
};

export type KnowledgeBasesUpdateFolderResponse = KnowledgeBasesUpdateFolderResponses[keyof KnowledgeBasesUpdateFolderResponses];

export type KnowledgeBasesMoveFolderData = {
    body: KnowledgeFolderMove;
    path: {
        /**
         * Knowledge Base Id
         */
        knowledge_base_id: string;
        /**
         * Folder Id
         */
        folder_id: string;
    };
    query?: never;
    url: '/api/v1/admin/knowledge-bases/{knowledge_base_id}/folders/{folder_id}/parent';
};

export type KnowledgeBasesMoveFolderErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type KnowledgeBasesMoveFolderError = KnowledgeBasesMoveFolderErrors[keyof KnowledgeBasesMoveFolderErrors];

export type KnowledgeBasesMoveFolderResponses = {
    /**
     * Successful Response
     */
    200: KnowledgeFolderPublic;
};

export type KnowledgeBasesMoveFolderResponse = KnowledgeBasesMoveFolderResponses[keyof KnowledgeBasesMoveFolderResponses];

export type KnowledgeBasesReadDirectoryData = {
    body?: never;
    path: {
        /**
         * Knowledge Base Id
         */
        knowledge_base_id: string;
    };
    query?: {
        /**
         * Folder Id
         */
        folder_id?: string | null;
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/admin/knowledge-bases/{knowledge_base_id}/entries';
};

export type KnowledgeBasesReadDirectoryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type KnowledgeBasesReadDirectoryError = KnowledgeBasesReadDirectoryErrors[keyof KnowledgeBasesReadDirectoryErrors];

export type KnowledgeBasesReadDirectoryResponses = {
    /**
     * Successful Response
     */
    200: KnowledgeDirectoryPublic;
};

export type KnowledgeBasesReadDirectoryResponse = KnowledgeBasesReadDirectoryResponses[keyof KnowledgeBasesReadDirectoryResponses];

export type KnowledgeBasesDeleteDirectoryEntriesData = {
    body: KnowledgeDirectoryDelete;
    path: {
        /**
         * Knowledge Base Id
         */
        knowledge_base_id: string;
    };
    query?: never;
    url: '/api/v1/admin/knowledge-bases/{knowledge_base_id}/directory/batch-delete';
};

export type KnowledgeBasesDeleteDirectoryEntriesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type KnowledgeBasesDeleteDirectoryEntriesError = KnowledgeBasesDeleteDirectoryEntriesErrors[keyof KnowledgeBasesDeleteDirectoryEntriesErrors];

export type KnowledgeBasesDeleteDirectoryEntriesResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type KnowledgeBasesDeleteDirectoryEntriesResponse = KnowledgeBasesDeleteDirectoryEntriesResponses[keyof KnowledgeBasesDeleteDirectoryEntriesResponses];

export type KnowledgeBasesCreateDocumentUploadData = {
    body: FileUploadRequest;
    path: {
        /**
         * Knowledge Base Id
         */
        knowledge_base_id: string;
    };
    query?: {
        /**
         * Folder Id
         */
        folder_id?: string | null;
    };
    url: '/api/v1/admin/knowledge-bases/{knowledge_base_id}/documents/uploads';
};

export type KnowledgeBasesCreateDocumentUploadErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type KnowledgeBasesCreateDocumentUploadError = KnowledgeBasesCreateDocumentUploadErrors[keyof KnowledgeBasesCreateDocumentUploadErrors];

export type KnowledgeBasesCreateDocumentUploadResponses = {
    /**
     * Successful Response
     */
    201: KnowledgeDocumentUploadPublic;
};

export type KnowledgeBasesCreateDocumentUploadResponse = KnowledgeBasesCreateDocumentUploadResponses[keyof KnowledgeBasesCreateDocumentUploadResponses];

export type KnowledgeBasesCreateWebpageDocumentData = {
    body: KnowledgeWebpageCreate;
    path: {
        /**
         * Knowledge Base Id
         */
        knowledge_base_id: string;
    };
    query?: {
        /**
         * Folder Id
         */
        folder_id?: string | null;
    };
    url: '/api/v1/admin/knowledge-bases/{knowledge_base_id}/documents/webpages';
};

export type KnowledgeBasesCreateWebpageDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type KnowledgeBasesCreateWebpageDocumentError = KnowledgeBasesCreateWebpageDocumentErrors[keyof KnowledgeBasesCreateWebpageDocumentErrors];

export type KnowledgeBasesCreateWebpageDocumentResponses = {
    /**
     * Successful Response
     */
    201: KnowledgeDocumentPublic;
};

export type KnowledgeBasesCreateWebpageDocumentResponse = KnowledgeBasesCreateWebpageDocumentResponses[keyof KnowledgeBasesCreateWebpageDocumentResponses];

export type KnowledgeBasesSearchKnowledgeBaseData = {
    body: KnowledgeSearchRequest;
    path: {
        /**
         * Knowledge Base Id
         */
        knowledge_base_id: string;
    };
    query?: never;
    url: '/api/v1/admin/knowledge-bases/{knowledge_base_id}/search';
};

export type KnowledgeBasesSearchKnowledgeBaseErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type KnowledgeBasesSearchKnowledgeBaseError = KnowledgeBasesSearchKnowledgeBaseErrors[keyof KnowledgeBasesSearchKnowledgeBaseErrors];

export type KnowledgeBasesSearchKnowledgeBaseResponses = {
    /**
     * Successful Response
     */
    200: KnowledgeSearchResultsPublic;
};

export type KnowledgeBasesSearchKnowledgeBaseResponse = KnowledgeBasesSearchKnowledgeBaseResponses[keyof KnowledgeBasesSearchKnowledgeBaseResponses];

export type KnowledgeDocumentsCompleteDocumentUploadData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/api/v1/admin/knowledge-documents/{document_id}/complete';
};

export type KnowledgeDocumentsCompleteDocumentUploadErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type KnowledgeDocumentsCompleteDocumentUploadError = KnowledgeDocumentsCompleteDocumentUploadErrors[keyof KnowledgeDocumentsCompleteDocumentUploadErrors];

export type KnowledgeDocumentsCompleteDocumentUploadResponses = {
    /**
     * Successful Response
     */
    200: KnowledgeDocumentPublic;
};

export type KnowledgeDocumentsCompleteDocumentUploadResponse = KnowledgeDocumentsCompleteDocumentUploadResponses[keyof KnowledgeDocumentsCompleteDocumentUploadResponses];

export type KnowledgeDocumentsDeleteDocumentData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/api/v1/admin/knowledge-documents/{document_id}';
};

export type KnowledgeDocumentsDeleteDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type KnowledgeDocumentsDeleteDocumentError = KnowledgeDocumentsDeleteDocumentErrors[keyof KnowledgeDocumentsDeleteDocumentErrors];

export type KnowledgeDocumentsDeleteDocumentResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type KnowledgeDocumentsDeleteDocumentResponse = KnowledgeDocumentsDeleteDocumentResponses[keyof KnowledgeDocumentsDeleteDocumentResponses];

export type KnowledgeDocumentsReadDocumentData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/api/v1/admin/knowledge-documents/{document_id}';
};

export type KnowledgeDocumentsReadDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type KnowledgeDocumentsReadDocumentError = KnowledgeDocumentsReadDocumentErrors[keyof KnowledgeDocumentsReadDocumentErrors];

export type KnowledgeDocumentsReadDocumentResponses = {
    /**
     * Successful Response
     */
    200: KnowledgeDocumentPublic;
};

export type KnowledgeDocumentsReadDocumentResponse = KnowledgeDocumentsReadDocumentResponses[keyof KnowledgeDocumentsReadDocumentResponses];

export type KnowledgeDocumentsReadDocumentPreviewData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/api/v1/admin/knowledge-documents/{document_id}/preview';
};

export type KnowledgeDocumentsReadDocumentPreviewErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type KnowledgeDocumentsReadDocumentPreviewError = KnowledgeDocumentsReadDocumentPreviewErrors[keyof KnowledgeDocumentsReadDocumentPreviewErrors];

export type KnowledgeDocumentsReadDocumentPreviewResponses = {
    /**
     * Successful Response
     */
    200: KnowledgeDocumentPreviewPublic;
};

export type KnowledgeDocumentsReadDocumentPreviewResponse = KnowledgeDocumentsReadDocumentPreviewResponses[keyof KnowledgeDocumentsReadDocumentPreviewResponses];

export type KnowledgeDocumentsReadDocumentChunksData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/admin/knowledge-documents/{document_id}/chunks';
};

export type KnowledgeDocumentsReadDocumentChunksErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type KnowledgeDocumentsReadDocumentChunksError = KnowledgeDocumentsReadDocumentChunksErrors[keyof KnowledgeDocumentsReadDocumentChunksErrors];

export type KnowledgeDocumentsReadDocumentChunksResponses = {
    /**
     * Successful Response
     */
    200: KnowledgeDocumentChunksPublic;
};

export type KnowledgeDocumentsReadDocumentChunksResponse = KnowledgeDocumentsReadDocumentChunksResponses[keyof KnowledgeDocumentsReadDocumentChunksResponses];

export type KnowledgeDocumentsDownloadOriginalDocumentData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/api/v1/admin/knowledge-documents/{document_id}/download';
};

export type KnowledgeDocumentsDownloadOriginalDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type KnowledgeDocumentsDownloadOriginalDocumentError = KnowledgeDocumentsDownloadOriginalDocumentErrors[keyof KnowledgeDocumentsDownloadOriginalDocumentErrors];

export type KnowledgeDocumentsDownloadOriginalDocumentResponses = {
    /**
     * Successful Response
     */
    200: FileCompletePublic;
};

export type KnowledgeDocumentsDownloadOriginalDocumentResponse = KnowledgeDocumentsDownloadOriginalDocumentResponses[keyof KnowledgeDocumentsDownloadOriginalDocumentResponses];

export type KnowledgeDocumentsMoveDocumentData = {
    body: KnowledgeDocumentMove;
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/api/v1/admin/knowledge-documents/{document_id}/folder';
};

export type KnowledgeDocumentsMoveDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type KnowledgeDocumentsMoveDocumentError = KnowledgeDocumentsMoveDocumentErrors[keyof KnowledgeDocumentsMoveDocumentErrors];

export type KnowledgeDocumentsMoveDocumentResponses = {
    /**
     * Successful Response
     */
    200: KnowledgeDocumentPublic;
};

export type KnowledgeDocumentsMoveDocumentResponse = KnowledgeDocumentsMoveDocumentResponses[keyof KnowledgeDocumentsMoveDocumentResponses];

export type KnowledgeDocumentsRetryDocumentData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/api/v1/admin/knowledge-documents/{document_id}/retry';
};

export type KnowledgeDocumentsRetryDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type KnowledgeDocumentsRetryDocumentError = KnowledgeDocumentsRetryDocumentErrors[keyof KnowledgeDocumentsRetryDocumentErrors];

export type KnowledgeDocumentsRetryDocumentResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type KnowledgeDocumentsRetryDocumentResponse = KnowledgeDocumentsRetryDocumentResponses[keyof KnowledgeDocumentsRetryDocumentResponses];

export type AgentReadConversationsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Search
         */
        search?: string | null;
        /**
         * Archived
         */
        archived?: boolean | null;
    };
    url: '/api/v1/agent/conversations';
};

export type AgentReadConversationsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AgentReadConversationsError = AgentReadConversationsErrors[keyof AgentReadConversationsErrors];

export type AgentReadConversationsResponses = {
    /**
     * Successful Response
     */
    200: ConversationsPublic;
};

export type AgentReadConversationsResponse = AgentReadConversationsResponses[keyof AgentReadConversationsResponses];

export type AgentCreateConversationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/agent/conversations';
};

export type AgentCreateConversationResponses = {
    /**
     * Successful Response
     */
    201: ConversationPublic;
};

export type AgentCreateConversationResponse = AgentCreateConversationResponses[keyof AgentCreateConversationResponses];

export type AgentGenerateConversationTitleData = {
    body: ConversationTitleRequest;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/v1/agent/conversations/{conversation_id}/generate-title';
};

export type AgentGenerateConversationTitleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AgentGenerateConversationTitleError = AgentGenerateConversationTitleErrors[keyof AgentGenerateConversationTitleErrors];

export type AgentGenerateConversationTitleResponses = {
    /**
     * Successful Response
     */
    200: ConversationPublic;
};

export type AgentGenerateConversationTitleResponse = AgentGenerateConversationTitleResponses[keyof AgentGenerateConversationTitleResponses];

export type AgentDeleteConversationData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/v1/agent/conversations/{conversation_id}';
};

export type AgentDeleteConversationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AgentDeleteConversationError = AgentDeleteConversationErrors[keyof AgentDeleteConversationErrors];

export type AgentDeleteConversationResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type AgentDeleteConversationResponse = AgentDeleteConversationResponses[keyof AgentDeleteConversationResponses];

export type AgentReadConversationData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/v1/agent/conversations/{conversation_id}';
};

export type AgentReadConversationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AgentReadConversationError = AgentReadConversationErrors[keyof AgentReadConversationErrors];

export type AgentReadConversationResponses = {
    /**
     * Successful Response
     */
    200: ConversationDetailPublic;
};

export type AgentReadConversationResponse = AgentReadConversationResponses[keyof AgentReadConversationResponses];

export type AgentRenameConversationData = {
    body: ConversationRenameRequest;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/v1/agent/conversations/{conversation_id}';
};

export type AgentRenameConversationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AgentRenameConversationError = AgentRenameConversationErrors[keyof AgentRenameConversationErrors];

export type AgentRenameConversationResponses = {
    /**
     * Successful Response
     */
    200: ConversationPublic;
};

export type AgentRenameConversationResponse = AgentRenameConversationResponses[keyof AgentRenameConversationResponses];

export type AgentArchiveConversationData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/v1/agent/conversations/{conversation_id}/archive';
};

export type AgentArchiveConversationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AgentArchiveConversationError = AgentArchiveConversationErrors[keyof AgentArchiveConversationErrors];

export type AgentArchiveConversationResponses = {
    /**
     * Successful Response
     */
    200: ConversationPublic;
};

export type AgentArchiveConversationResponse = AgentArchiveConversationResponses[keyof AgentArchiveConversationResponses];

export type AgentUnarchiveConversationData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/v1/agent/conversations/{conversation_id}/unarchive';
};

export type AgentUnarchiveConversationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AgentUnarchiveConversationError = AgentUnarchiveConversationErrors[keyof AgentUnarchiveConversationErrors];

export type AgentUnarchiveConversationResponses = {
    /**
     * Successful Response
     */
    200: ConversationPublic;
};

export type AgentUnarchiveConversationResponse = AgentUnarchiveConversationResponses[keyof AgentUnarchiveConversationResponses];

export type ContentOperationsReadBilibiliRankingData = {
    body?: never;
    path?: never;
    query?: {
        category?: BilibiliRankingCategoryCode;
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/admin/content-operations/rankings/bilibili';
};

export type ContentOperationsReadBilibiliRankingErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ContentOperationsReadBilibiliRankingError = ContentOperationsReadBilibiliRankingErrors[keyof ContentOperationsReadBilibiliRankingErrors];

export type ContentOperationsReadBilibiliRankingResponses = {
    /**
     * Successful Response
     */
    200: BilibiliRankingPublic;
};

export type ContentOperationsReadBilibiliRankingResponse = ContentOperationsReadBilibiliRankingResponses[keyof ContentOperationsReadBilibiliRankingResponses];

export type InfluencerMarketingReadInfluencerAccountsData = {
    body?: never;
    path?: never;
    query?: {
        platform?: InfluencerPlatformCode;
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Search
         */
        search?: string | null;
        sort_by?: InfluencerAccountSortBy;
        sort_order?: InfluencerSortOrder;
    };
    url: '/api/v1/admin/influencer-marketing/accounts';
};

export type InfluencerMarketingReadInfluencerAccountsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type InfluencerMarketingReadInfluencerAccountsError = InfluencerMarketingReadInfluencerAccountsErrors[keyof InfluencerMarketingReadInfluencerAccountsErrors];

export type InfluencerMarketingReadInfluencerAccountsResponses = {
    /**
     * Successful Response
     */
    200: InfluencerAccountsPublic;
};

export type InfluencerMarketingReadInfluencerAccountsResponse = InfluencerMarketingReadInfluencerAccountsResponses[keyof InfluencerMarketingReadInfluencerAccountsResponses];

export type FilesCreateFileUploadData = {
    body: FileUploadRequest;
    path?: never;
    query?: never;
    url: '/api/v1/files';
};

export type FilesCreateFileUploadErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FilesCreateFileUploadError = FilesCreateFileUploadErrors[keyof FilesCreateFileUploadErrors];

export type FilesCreateFileUploadResponses = {
    /**
     * Successful Response
     */
    201: FileUploadPublic;
};

export type FilesCreateFileUploadResponse = FilesCreateFileUploadResponses[keyof FilesCreateFileUploadResponses];

export type FilesCompleteFileUploadData = {
    body?: never;
    path: {
        /**
         * File Id
         */
        file_id: string;
    };
    query?: never;
    url: '/api/v1/files/{file_id}/complete';
};

export type FilesCompleteFileUploadErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FilesCompleteFileUploadError = FilesCompleteFileUploadErrors[keyof FilesCompleteFileUploadErrors];

export type FilesCompleteFileUploadResponses = {
    /**
     * Successful Response
     */
    200: FileCompletePublic;
};

export type FilesCompleteFileUploadResponse = FilesCompleteFileUploadResponses[keyof FilesCompleteFileUploadResponses];

export type FilesDeleteUnreferencedFileData = {
    body?: never;
    path: {
        /**
         * File Id
         */
        file_id: string;
    };
    query?: never;
    url: '/api/v1/files/{file_id}';
};

export type FilesDeleteUnreferencedFileErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FilesDeleteUnreferencedFileError = FilesDeleteUnreferencedFileErrors[keyof FilesDeleteUnreferencedFileErrors];

export type FilesDeleteUnreferencedFileResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type FilesDeleteUnreferencedFileResponse = FilesDeleteUnreferencedFileResponses[keyof FilesDeleteUnreferencedFileResponses];

export type FilesGetFileDownloadUrlData = {
    body?: never;
    path: {
        /**
         * File Id
         */
        file_id: string;
    };
    query?: never;
    url: '/api/v1/files/{file_id}';
};

export type FilesGetFileDownloadUrlErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FilesGetFileDownloadUrlError = FilesGetFileDownloadUrlErrors[keyof FilesGetFileDownloadUrlErrors];

export type FilesGetFileDownloadUrlResponses = {
    /**
     * Successful Response
     */
    200: FileCompletePublic;
};

export type FilesGetFileDownloadUrlResponse = FilesGetFileDownloadUrlResponses[keyof FilesGetFileDownloadUrlResponses];

export type SkillsCreateMdSkillData = {
    body: SkillMdRequest;
    path?: never;
    query?: never;
    url: '/api/v1/skills/md';
};

export type SkillsCreateMdSkillErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SkillsCreateMdSkillError = SkillsCreateMdSkillErrors[keyof SkillsCreateMdSkillErrors];

export type SkillsCreateMdSkillResponses = {
    /**
     * Successful Response
     */
    201: SkillPublic;
};

export type SkillsCreateMdSkillResponse = SkillsCreateMdSkillResponses[keyof SkillsCreateMdSkillResponses];

export type SkillsCreateZipSkillData = {
    body: BodySkillsCreateZipSkill;
    path?: never;
    query?: never;
    url: '/api/v1/skills/zip';
};

export type SkillsCreateZipSkillErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SkillsCreateZipSkillError = SkillsCreateZipSkillErrors[keyof SkillsCreateZipSkillErrors];

export type SkillsCreateZipSkillResponses = {
    /**
     * Successful Response
     */
    201: SkillPublic;
};

export type SkillsCreateZipSkillResponse = SkillsCreateZipSkillResponses[keyof SkillsCreateZipSkillResponses];

export type SkillsReadSkillsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Search
         */
        search?: string | null;
    };
    url: '/api/v1/skills';
};

export type SkillsReadSkillsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SkillsReadSkillsError = SkillsReadSkillsErrors[keyof SkillsReadSkillsErrors];

export type SkillsReadSkillsResponses = {
    /**
     * Successful Response
     */
    200: SkillsPublic;
};

export type SkillsReadSkillsResponse = SkillsReadSkillsResponses[keyof SkillsReadSkillsResponses];

export type SkillsDeleteSkillData = {
    body?: never;
    path: {
        /**
         * Skill Name
         */
        skill_name: string;
    };
    query?: never;
    url: '/api/v1/skills/{skill_name}';
};

export type SkillsDeleteSkillErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SkillsDeleteSkillError = SkillsDeleteSkillErrors[keyof SkillsDeleteSkillErrors];

export type SkillsDeleteSkillResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type SkillsDeleteSkillResponse = SkillsDeleteSkillResponses[keyof SkillsDeleteSkillResponses];

export type SkillsReadSkillData = {
    body?: never;
    path: {
        /**
         * Skill Name
         */
        skill_name: string;
    };
    query?: never;
    url: '/api/v1/skills/{skill_name}';
};

export type SkillsReadSkillErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SkillsReadSkillError = SkillsReadSkillErrors[keyof SkillsReadSkillErrors];

export type SkillsReadSkillResponses = {
    /**
     * Successful Response
     */
    200: SkillPublic;
};

export type SkillsReadSkillResponse = SkillsReadSkillResponses[keyof SkillsReadSkillResponses];

export type SkillsReadSkillFileData = {
    body?: never;
    path: {
        /**
         * Skill Name
         */
        skill_name: string;
        /**
         * File Path
         */
        file_path: string;
    };
    query?: never;
    url: '/api/v1/skills/{skill_name}/files/{file_path}';
};

export type SkillsReadSkillFileErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SkillsReadSkillFileError = SkillsReadSkillFileErrors[keyof SkillsReadSkillFileErrors];

export type SkillsReadSkillFileResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AgentReadModelsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/agent/models';
};

export type AgentReadModelsResponses = {
    /**
     * Successful Response
     */
    200: AgentModelsPublic;
};

export type AgentReadModelsResponse = AgentReadModelsResponses[keyof AgentReadModelsResponses];

export type AgentCreateAgentRunData = {
    body: AgentChatRequest;
    path?: never;
    query?: never;
    url: '/api/v1/agent/runs';
};

export type AgentCreateAgentRunErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AgentCreateAgentRunError = AgentCreateAgentRunErrors[keyof AgentCreateAgentRunErrors];

export type AgentCreateAgentRunResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AgentReadAgentRunResumeStateData = {
    body: AgentRunResumeStateRequest;
    path?: never;
    query?: never;
    url: '/api/v1/agent/runs/resume-state';
};

export type AgentReadAgentRunResumeStateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AgentReadAgentRunResumeStateError = AgentReadAgentRunResumeStateErrors[keyof AgentReadAgentRunResumeStateErrors];

export type AgentReadAgentRunResumeStateResponses = {
    /**
     * Successful Response
     */
    200: AgentRunResumeStatePublic;
    /**
     * 没有活动运行
     */
    204: void;
};

export type AgentReadAgentRunResumeStateResponse = AgentReadAgentRunResumeStateResponses[keyof AgentReadAgentRunResumeStateResponses];

export type AgentResumeAgentRunData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/agent/runs/{run_id}/stream';
};

export type AgentResumeAgentRunErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AgentResumeAgentRunError = AgentResumeAgentRunErrors[keyof AgentResumeAgentRunErrors];

export type AgentResumeAgentRunResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AgentCancelAgentRunData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/agent/runs/{run_id}/cancel';
};

export type AgentCancelAgentRunErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AgentCancelAgentRunError = AgentCancelAgentRunErrors[keyof AgentCancelAgentRunErrors];

export type AgentCancelAgentRunResponses = {
    /**
     * Successful Response
     */
    202: unknown;
};
