INTERNAL_OPERATIONS = {
    "knowledge-bases-read_knowledge_bases": "knowledge_bases_list",
    "knowledge-bases-create_knowledge_base": "knowledge_base_create",
    "knowledge-bases-read_knowledge_base": "knowledge_base_get",
    "knowledge-bases-update_knowledge_base": "knowledge_base_update",
    "knowledge-bases-delete_knowledge_base": "knowledge_base_delete",
    "knowledge-bases-create_folder": "knowledge_folder_create",
    "knowledge-bases-read_folders": "knowledge_folders_list",
    "knowledge-bases-update_folder": "knowledge_folder_update",
    "knowledge-bases-move_folder": "knowledge_folder_move",
    "knowledge-bases-read_directory": "knowledge_directory_list",
    "knowledge-bases-delete_directory_entries": "knowledge_entries_delete",
    "knowledge-bases-create_document_upload": "knowledge_document_upload_create",
    "knowledge-documents-complete_document_upload": "knowledge_document_upload_complete",
    "knowledge-documents-read_document": "knowledge_document_get",
    "knowledge-documents-read_document_preview": "knowledge_document_preview",
    "knowledge-documents-read_document_chunks": "knowledge_document_chunks_list",
    "knowledge-documents-download_original_document": "knowledge_document_download",
    "knowledge-documents-move_document": "knowledge_document_move",
    "knowledge-documents-retry_document": "knowledge_document_retry",
    "knowledge-documents-delete_document": "knowledge_document_delete",
    "knowledge-bases-create_webpage_document": "knowledge_webpage_import",
    "knowledge-bases-search_knowledge_base": "knowledge_search",
    "brand-marketing-read_regional_data": "regional_data_query",
    "content-operations-read_bilibili_ranking": "bilibili_ranking_query",
    "influencer-marketing-read_influencer_accounts": "influencer_accounts_query",
}

EXTERNAL_OPERATIONS = {
    "external-knowledge-read_external_knowledge_bases": "knowledge_bases_list",
    "external-knowledge-search_external_knowledge_base": "knowledge_search",
    "brand-marketing-read_regional_data": "regional_data_query",
    "content-operations-read_bilibili_ranking": "bilibili_ranking_query",
    "influencer-marketing-read_influencer_accounts": "influencer_accounts_query",
}
