INTERNAL_OPERATIONS = {
    "file-libraries-read_file_libraries": "file_libraries_list",
    "file-libraries-create_file_library": "file_library_create",
    "file-libraries-create_folder": "library_folder_create",
    "file-libraries-move_folder": "library_folder_move",
    "file-libraries-read_directory": "library_directory_list",
    "file-libraries-delete_directory_entries": "library_entries_delete",
    "file-libraries-create_document_upload": "library_document_upload_create",
    "library-documents-complete_document_upload": "library_document_upload_complete",
    "library-documents-download_original_document": "library_document_download",
    "library-documents-move_document": "library_document_move",
    "knowledge-bases-read_knowledge_bases": "knowledge_bases_list",
    "knowledge-bases-create_knowledge_base": "knowledge_base_create",
    "knowledge-bases-create_folder": "knowledge_folder_create",
    "knowledge-bases-move_folder": "knowledge_folder_move",
    "knowledge-bases-read_directory": "knowledge_directory_list",
    "knowledge-bases-delete_directory_entries": "knowledge_entries_delete",
    "knowledge-bases-create_document_upload": "knowledge_document_upload_create",
    "knowledge-documents-complete_document_upload": "knowledge_document_upload_complete",
    "knowledge-documents-download_original_document": "knowledge_document_download",
    "knowledge-documents-move_document": "knowledge_document_move",
    "knowledge-bases-create_webpage_document": "knowledge_webpage_import",
    "knowledge-bases-search_knowledge_base": "knowledge_search",
    "brand-marketing-read_regional_data": "regional_data_query",
    "content-operations-read_bilibili_ranking": "bilibili_ranking_query",
    "influencer-marketing-read_influencer_accounts": "influencer_accounts_query",
}

EXTERNAL_OPERATIONS = {
    "external-knowledge-read_external_knowledge_bases": "knowledge_bases_list",
    "external-knowledge-search_external_knowledge_base": "knowledge_search",
    "brand-marketing-read_regional_data": "regional_data_query",
    "content-operations-read_bilibili_ranking": "bilibili_ranking_query",
    "influencer-marketing-read_influencer_accounts": "influencer_accounts_query",
}
